#!/usr/bin/env python3
"""Sync embedded themes from the GPUI Kit release pinned in Cargo.lock."""

import io
import json
import re
import sys
import tarfile
from pathlib import Path, PurePosixPath
from urllib.request import urlopen

import tomllib

ROOT = Path(__file__).resolve().parent.parent


def download_archive(url):
    with urlopen(url, timeout=120) as response:
        return tarfile.open(fileobj=io.BytesIO(response.read()), mode="r:gz")


def read_member(archive, name):
    with archive.extractfile(name) as file:
        return file.read()


def main():
    with (ROOT / "Cargo.lock").open("rb") as file:
        packages = tomllib.load(file)["package"]
    versions = [package["version"] for package in packages if package["name"] == "gpui-kit"]
    if len(versions) != 1:
        raise ValueError("Expected exactly one GPUI Kit version in Cargo.lock")
    version = versions[0]

    with download_archive(f"https://static.crates.io/crates/gpui-kit/gpui-kit-{version}.crate") as archive:
        metadata = json.loads(read_member(archive, f"gpui-kit-{version}/.cargo_vcs_info.json"))
    revision = metadata["git"]["sha1"]
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("The published GPUI Kit crate contains an invalid source revision")

    themes = {}
    directory = PurePosixPath(f"gpui-kit-{revision}/themes")
    with download_archive(f"https://codeload.github.com/longbridge/gpui-kit/tar.gz/{revision}") as archive:
        for member in archive.getmembers():
            path = PurePosixPath(member.name)
            if not member.isfile() or path.parent != directory or path.suffix != ".json":
                continue
            if not re.fullmatch(r"[a-z0-9_-]+\.json", path.name):
                raise ValueError(f"Unsupported theme filename: {path.name}")
            content = read_member(archive, member.name)
            variants = json.loads(content.decode("utf-8")).get("themes")
            if not isinstance(variants, list) or not variants:
                raise ValueError(f"Invalid theme file: {path.name}")
            themes[path.name] = content
    if not themes:
        raise ValueError(f"GPUI Kit {version} contains no theme files")

    embedded = (
        "// Generated by just sync-themes; do not edit.\n"
        f"// GPUI Kit {version}, source revision {revision}.\n\n"
        "pub(crate) const THEMES: &[(&str, &str)] = &[\n"
        + "".join(f'    ("{name}", include_str!("../themes/{name}")),\n' for name in sorted(themes))
        + "];\n"
    )
    # All downloads and validation finish before changing the checked-in files.
    destination = ROOT / "themes"
    destination.mkdir(exist_ok=True)
    for name, content in themes.items():
        (destination / name).write_bytes(content)
    for stale in destination.glob("*.json"):
        if stale.name not in themes:
            stale.unlink()
    (ROOT / "src/bundled_themes.rs").write_text(embedded, encoding="utf-8", newline="\n")
    print(f"Synced {len(themes)} theme files from gpui-kit {version} ({revision})")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, tarfile.TarError) as error:
        sys.exit(f"Could not sync themes: {error}")
